language: php
php:
  - 7.0
  - 7.1
  - nightly
before_script:
  - phpenv config-rm xdebug.ini || echo 'xdebug.ini not installed'
  - composer self-update
  - composer install --prefer-source
script:
  - composer test
env:
  - REPORT_EXIT_STATUS=1
notifications:
  slack:
    secure: hUakgvEjbH+MHhEMybqEpO3o2im6qfFIOc+nEmqSNpsMD2fnM61Z6XhR7slCXrfuhfLzsiwSg/MN+ZxBpHCh39z7rQ0dSCkBT/sCF2rvBfQuIt5fI3yrxL9EqYeIMT/ivRezj4bYUa2kBnMJcNLsJEsHou8m77aNjHNy/53RHCLR6+wkFR0XNWDQV0LZeFXgdLyiU7+3Ln3lDV2RGSfKlGQMvT/fsGLHamn4Iod5z9gt5lnEGQ6zLA/G19nM7KA9c3YybaXvpkiAUmEY5JYZ+eNU73vHfBG/OvOSGAT4889lEM36cAq9qnrJQetteHZQaVgy7jTSvEBZUvyTI18LWrSvzN4jqr+eYyJMV49IAMSHdXm1NC4e/e6YCT7psjYpBYazMt83iQx/3vvwvuXeZ1KEquUDvZ8vK2ugF7/RMCgDDAPrt3HxZQK71yMrouZkdoPWQbc3IlwSid3TprtcwkksoEncgI82XOlpTduuxNQCU7Tn0pbkJA9X+UBb+W/Eaex6bJhikmsvNPxamrgt3QJebFUNxohKmZ4pB3TpVfg714PY/bgzB6Wp/CPka8sJPzIQxwKlwNpFc78I74eyrrdm7rwHra5boz+5YSh+WryeBaKa4MMBi7Jot0MPZbGFBPHQSGfcBAjkRofgf2T/4E023NgKdyIgLm1/V3oXec4=
